# Generated by Django 3.0.7 on 2020-07-05 07:34

from django.db import migrations, models
import location_field.models.plain


class Migration(migrations.Migration):

    dependencies = [
        ('driver', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='driver',
            name='address',
        ),
        migrations.AddField(
            model_name='driver',
            name='city',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='driver',
            name='image',
            field=models.ImageField(default='', upload_to='mechanic_img'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='driver',
            name='location',
            field=location_field.models.plain.PlainLocationField(default='', max_length=63),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='driver',
            name='first_name',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='driver',
            name='last_name',
            field=models.CharField(max_length=150),
        ),
    ]
