# Generated by Django 3.0.7 on 2020-07-18 05:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('driver', '0003_auto_20200705_1108'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='created_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='driver', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='driver',
            name='image',
            field=sorl.thumbnail.fields.ImageField(upload_to='driver_img'),
        ),
    ]
