# Generated by Django 3.0.7 on 2020-07-18 10:33

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import location_field.models.plain
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Old_Parts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('image', sorl.thumbnail.fields.ImageField(upload_to='old_parts_img')),
                ('phone_number', models.CharField(blank=True, max_length=17, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')])),
                ('city', models.CharField(max_length=255)),
                ('location', location_field.models.plain.PlainLocationField(max_length=63)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='old_parts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Old_Part',
                'verbose_name_plural': 'Old_Parts',
            },
        ),
    ]
