# Generated by Django 3.0.7 on 2020-07-01 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='service',
            field=models.CharField(choices=[('MIC', 'mechanic'), ('AUR', 'auto_roof'), ('SPR', 'spare_parts'), ('OLD', 'old_parts')], default='MIC', max_length=4),
        ),
    ]
