# Generated by Django 3.0.7 on 2020-07-05 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0002_auto_20200701_0934'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='service',
            field=models.CharField(choices=[('MIC', 'mechanic'), ('AUR', 'auto_roof'), ('SPR', 'spare_parts'), ('OLD', 'old_parts'), ('DRI', 'driver')], default='MIC', max_length=10),
        ),
    ]
