# Generated by Django 3.0.7 on 2020-07-13 07:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mechanic', '0002_mechanic_created_by'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mechanic',
            old_name='created_by',
            new_name='user',
        ),
    ]
