# Generated by Django 3.0.7 on 2020-07-14 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mechanic', '0003_auto_20200713_1050'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mechanic',
            name='user',
        ),
    ]
