# Generated by Django 3.0.7 on 2020-07-16 05:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mechanic', '0004_remove_mechanic_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='mechanic',
            name='created_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='mechanic', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
