# Generated by Django 3.0.7 on 2020-07-16 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mechanic', '0005_mechanic_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='mechanic',
            name='image_height',
            field=models.PositiveIntegerField(blank=True, default='451', editable=False, null=True),
        ),
        migrations.AddField(
            model_name='mechanic',
            name='image_width',
            field=models.PositiveIntegerField(blank=True, default='360', editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='mechanic',
            name='image',
            field=models.ImageField(blank=True, help_text='Mechanic Picture', null=True, upload_to='mechanic_img', verbose_name='Mechanic Picture'),
        ),
    ]
