# Generated by Django 3.0.7 on 2020-07-16 09:47

from django.db import migrations
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('mechanic', '0006_auto_20200716_1027'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mechanic',
            name='image_height',
        ),
        migrations.RemoveField(
            model_name='mechanic',
            name='image_width',
        ),
        migrations.AlterField(
            model_name='mechanic',
            name='image',
            field=sorl.thumbnail.fields.ImageField(default='', upload_to='mechanic_img'),
            preserve_default=False,
        ),
    ]
