# Generated by Django 3.0.7 on 2020-07-19 06:02

from django.db import migrations
import mapbox_location_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('mechanic', '0007_auto_20200716_1247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mechanic',
            name='location',
            field=mapbox_location_field.models.LocationField(map_attrs={}),
        ),
    ]
