# Generated by Django 3.0.7 on 2020-07-19 06:15

from django.db import migrations
import mapbox_location_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('mechanic', '0008_auto_20200719_0902'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mechanic',
            name='location',
            field=mapbox_location_field.models.LocationField(map_attrs={'center': [0, 0], 'marker_color': 'blue'}),
        ),
    ]
